add: android sdk init
GoodDollar/ReactNativeFaceTec pull request #2
Opened 2020-12-30 15:11 UTC by mauriguz

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

About # (link your issue here)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

# Checklist:
- [ ] PR title matches follow: (Feature|Bug|Chore) Task Name
- [ ] My code follows the style guidelines of this project
- [ ] I have followed all the instructions described in the initial task (check Definitions of Done)
- [ ] I have performed a self-review of my own code
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have added reference to a related issue in the repository
- [ ] I have added a detailed description of the changes proposed in the pull request. I am as descriptive as possible, assisting reviewers as much as possible.
- [ ] I have added screenshots related to my pull request (for frontend tasks)
- [ ] I have pasted a gif showing the feature.
- [ ] @mentions of the person or team responsible for reviewing proposed changes

2020-12-30 15:40 UTC, serdiukov-o-nordwhale requested changes

2020-12-30 15:40 UTC, serdiukov-o-nordwhale commented on android/src/main/java/org/gooddollar/FaceTecModule.java
> +                if (!licenseText.isEmpty()) {
licenseText could also be null

2020-12-30 15:40 UTC, serdiukov-o-nordwhale commented on android/src/main/java/org/gooddollar/FaceTecModule.java
> +                if (sdkStatus == FaceTecSDKStatus.NEVER_INITIALIZED) {
1. make it multi-line like on web & IOS
2. replace word "Simulator" to "Android Emulator"

2020-12-30 15:40 UTC, serdiukov-o-nordwhale commented on android/src/main/java/org/gooddollar/FaceTecModule.java
> +                if (sdkStatus == FaceTecSDKStatus.NEVER_INITIALIZED) {
```suggestion

                if (sdkStatus == FaceTecSDKStatus.NEVER_INITIALIZED) {
```

2020-12-30 15:40 UTC, serdiukov-o-nordwhale commented on android/src/main/java/org/gooddollar/FaceTecModule.java
> +
```suggestion
```

2020-12-30 15:40 UTC, serdiukov-o-nordwhale commented on android/src/main/java/org/gooddollar/FaceTecModule.java
> +
```suggestion
```

2020-12-30 15:40 UTC, serdiukov-o-nordwhale commented on android/src/main/java/org/gooddollar/FaceTecModule.java
> +    private FaceTecSDKStatus getSDKStatus(Activity activity) {
it seems we don't need  a separate method
on IOS implementation getStatus is needed to be wrapped onto the main thread
if you don't need additional logic here, just use FaceTecSDK.getStatus(activity) everywhere

2020-12-30 15:41 UTC, serdiukov-o-nordwhale commented
Please also append your code with the comments describing the flow

2020-12-31 14:15 UTC, serdiukov-o-nordwhale commented on android/src/main/java/org/gooddollar/FaceTecModule.java
> +                    customMessage = "Initialize wasn't attempted as Android Emulator has been detected." + newLine + "FaceTec SDK could be ran on the real devices only";
```suggestion
                    customMessage = "Initialize wasn't attempted as Android Emulator has been detected."
                        + "FaceTec SDK could be ran on the real devices only";
```

2020-12-31 14:15 UTC, serdiukov-o-nordwhale approved these changes

2020-12-31 14:15 UTC, mauriguz commented on android/src/main/java/org/gooddollar/FaceTecModule.java
> +                String newLine = System.getProperty("line.separator");
```suggestion

```

2020-12-31 14:15 UTC, serdiukov-o-nordwhale commented on android/src/main/java/org/gooddollar/FaceTecModule.java
> +                String newLine = System.getProperty("line.separator");
```suggestion
```

2020-12-31 14:16 UTC, serdiukov-o-nordwhale approved these changes

2020-12-31 14:16 UTC, merged